AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  One:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/one
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /one
            Method: get
  Two:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/two
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /two
            Method: get
  Three:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/three
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /three
            Method: get
